CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

START TRANSACTION;
CREATE TABLE "AspNetRoles" (
    "Id" text NOT NULL,
    description text,
    "creationDate" timestamp without time zone NOT NULL,
    "Name" character varying(256),
    "NormalizedName" character varying(256),
    "ConcurrencyStamp" text,
    CONSTRAINT "PK_AspNetRoles" PRIMARY KEY ("Id")
);

CREATE TABLE "City" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Name" text,
    CONSTRAINT "PK_City" PRIMARY KEY ("Id")
);

CREATE TABLE "EventType" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Name" text,
    CONSTRAINT "PK_EventType" PRIMARY KEY ("Id")
);

CREATE TABLE "AspNetRoleClaims" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "RoleId" text NOT NULL,
    "ClaimType" text,
    "ClaimValue" text,
    CONSTRAINT "PK_AspNetRoleClaims" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_AspNetRoleClaims_AspNetRoles_RoleId" FOREIGN KEY ("RoleId") REFERENCES "AspNetRoles" ("Id") ON DELETE CASCADE
);

CREATE TABLE "AspNetUsers" (
    "Id" text NOT NULL,
    "FirstName" text,
    "LastName" text,
    "CityId" integer,
    "Address" text,
    "PostalCode" text,
    "HasRequestedVenueManagerRole" boolean NOT NULL,
    "VenueManagerRequestDate" timestamp without time zone,
    "VenueManagerRequestReason" text,
    "VenueManagerRequestStatus" text,
    "HasRequestedEventManagerRole" boolean NOT NULL,
    "EventManagerRequestDate" timestamp without time zone,
    "EventManagerRequestReason" text,
    "EventManagerRequestStatus" text,
    "HasRequestedSuperOrganizerRole" boolean NOT NULL,
    "SuperOrganizerRequestDate" timestamp without time zone,
    "SuperOrganizerRequestReason" text,
    "SuperOrganizerRequestStatus" text,
    "UserName" character varying(256),
    "NormalizedUserName" character varying(256),
    "Email" character varying(256),
    "NormalizedEmail" character varying(256),
    "EmailConfirmed" boolean NOT NULL,
    "PasswordHash" text,
    "SecurityStamp" text,
    "ConcurrencyStamp" text,
    "PhoneNumber" text,
    "PhoneNumberConfirmed" boolean NOT NULL,
    "TwoFactorEnabled" boolean NOT NULL,
    "LockoutEnd" timestamp with time zone,
    "LockoutEnabled" boolean NOT NULL,
    "AccessFailedCount" integer NOT NULL,
    CONSTRAINT "PK_AspNetUsers" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_AspNetUsers_City_CityId" FOREIGN KEY ("CityId") REFERENCES "City" ("Id") ON DELETE RESTRICT
);

CREATE TABLE "AspNetUserClaims" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "UserId" text NOT NULL,
    "ClaimType" text,
    "ClaimValue" text,
    CONSTRAINT "PK_AspNetUserClaims" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_AspNetUserClaims_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE
);

CREATE TABLE "AspNetUserLogins" (
    "LoginProvider" character varying(128) NOT NULL,
    "ProviderKey" character varying(128) NOT NULL,
    "ProviderDisplayName" text,
    "UserId" text NOT NULL,
    CONSTRAINT "PK_AspNetUserLogins" PRIMARY KEY ("LoginProvider", "ProviderKey"),
    CONSTRAINT "FK_AspNetUserLogins_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE
);

CREATE TABLE "AspNetUserRoles" (
    "UserId" text NOT NULL,
    "RoleId" text NOT NULL,
    CONSTRAINT "PK_AspNetUserRoles" PRIMARY KEY ("UserId", "RoleId"),
    CONSTRAINT "FK_AspNetUserRoles_AspNetRoles_RoleId" FOREIGN KEY ("RoleId") REFERENCES "AspNetRoles" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_AspNetUserRoles_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE
);

CREATE TABLE "AspNetUserTokens" (
    "UserId" text NOT NULL,
    "LoginProvider" character varying(128) NOT NULL,
    "Name" character varying(128) NOT NULL,
    "Value" text,
    CONSTRAINT "PK_AspNetUserTokens" PRIMARY KEY ("UserId", "LoginProvider", "Name"),
    CONSTRAINT "FK_AspNetUserTokens_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE
);

CREATE TABLE "Venue" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Name" text,
    "Address" text,
    "CityId" integer NOT NULL,
    "PostalCode" text,
    "Phone" text,
    "VenueUrl" text,
    "SocialMediaUrl" text,
    "UserId" text,
    "imgUrl" text,
    CONSTRAINT "PK_Venue" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Venue_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES "AspNetUsers" ("Id") ON DELETE RESTRICT,
    CONSTRAINT "FK_Venue_City_CityId" FOREIGN KEY ("CityId") REFERENCES "City" ("Id") ON DELETE RESTRICT
);

CREATE TABLE "Layout" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "AreaName" text,
    "Width" numeric(18,2) NOT NULL,
    "Height" numeric(18,2) NOT NULL,
    "Top" numeric(18,2) NOT NULL,
    "Left" numeric(18,2) NOT NULL,
    "Rotate" numeric(18,2) NOT NULL,
    "Desc" text,
    "VenueId" integer NOT NULL,
    CONSTRAINT "PK_Layout" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Layout_Venue_VenueId" FOREIGN KEY ("VenueId") REFERENCES "Venue" ("Id") ON DELETE RESTRICT
);

CREATE TABLE "VenueCategory" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "VenueId" integer NOT NULL,
    "CategoryId" integer,
    CONSTRAINT "PK_VenueCategory" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_VenueCategory_EventType_CategoryId" FOREIGN KEY ("CategoryId") REFERENCES "EventType" ("Id") ON DELETE RESTRICT,
    CONSTRAINT "FK_VenueCategory_Venue_VenueId" FOREIGN KEY ("VenueId") REFERENCES "Venue" ("Id") ON DELETE RESTRICT
);

CREATE TABLE "Event" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Name" text,
    "StartDateTime" timestamp without time zone NOT NULL,
    "EndTime" timestamp without time zone NOT NULL,
    "EventTypeId" integer NOT NULL,
    "VenueId" integer NOT NULL,
    "LayoutId" integer,
    "ParentEventId" integer,
    "ImagePath" text,
    CONSTRAINT "PK_Event" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Event_EventType_EventTypeId" FOREIGN KEY ("EventTypeId") REFERENCES "EventType" ("Id") ON DELETE RESTRICT,
    CONSTRAINT "FK_Event_Event_ParentEventId" FOREIGN KEY ("ParentEventId") REFERENCES "Event" ("Id") ON DELETE RESTRICT,
    CONSTRAINT "FK_Event_Layout_LayoutId" FOREIGN KEY ("LayoutId") REFERENCES "Layout" ("Id") ON DELETE RESTRICT,
    CONSTRAINT "FK_Event_Venue_VenueId" FOREIGN KEY ("VenueId") REFERENCES "Venue" ("Id") ON DELETE RESTRICT
);

CREATE TABLE "Seat" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "X" numeric(18,2) NOT NULL,
    "Y" numeric(18,2) NOT NULL,
    "Name" text,
    "Available" boolean NOT NULL,
    "LayoutId" integer NOT NULL,
    CONSTRAINT "PK_Seat" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Seat_Layout_LayoutId" FOREIGN KEY ("LayoutId") REFERENCES "Layout" ("Id") ON DELETE RESTRICT
);

CREATE TABLE "Reservation" (
    "ID" integer GENERATED BY DEFAULT AS IDENTITY,
    "UserId" text,
    "SeatId" integer NOT NULL,
    "EventId" integer NOT NULL,
    "Date" timestamp without time zone NOT NULL,
    "Duration" bigint NOT NULL,
    "IsPastReservation" boolean NOT NULL,
    "Attended" boolean,
    "Review" text,
    "Rating" integer,
    CONSTRAINT "PK_Reservation" PRIMARY KEY ("ID"),
    CONSTRAINT "FK_Reservation_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES "AspNetUsers" ("Id") ON DELETE RESTRICT,
    CONSTRAINT "FK_Reservation_Event_EventId" FOREIGN KEY ("EventId") REFERENCES "Event" ("Id") ON DELETE RESTRICT,
    CONSTRAINT "FK_Reservation_Seat_SeatId" FOREIGN KEY ("SeatId") REFERENCES "Seat" ("Id") ON DELETE RESTRICT
);

CREATE INDEX "IX_AspNetRoleClaims_RoleId" ON "AspNetRoleClaims" ("RoleId");

CREATE UNIQUE INDEX "RoleNameIndex" ON "AspNetRoles" ("NormalizedName");

CREATE INDEX "IX_AspNetUserClaims_UserId" ON "AspNetUserClaims" ("UserId");

CREATE INDEX "IX_AspNetUserLogins_UserId" ON "AspNetUserLogins" ("UserId");

CREATE INDEX "IX_AspNetUserRoles_RoleId" ON "AspNetUserRoles" ("RoleId");

CREATE INDEX "EmailIndex" ON "AspNetUsers" ("NormalizedEmail");

CREATE INDEX "IX_AspNetUsers_CityId" ON "AspNetUsers" ("CityId");

CREATE UNIQUE INDEX "UserNameIndex" ON "AspNetUsers" ("NormalizedUserName");

CREATE INDEX "IX_Event_EventTypeId" ON "Event" ("EventTypeId");

CREATE INDEX "IX_Event_ParentEventId" ON "Event" ("ParentEventId");

CREATE INDEX "IX_Event_LayoutId" ON "Event" ("LayoutId");

CREATE INDEX "IX_Event_VenueId" ON "Event" ("VenueId");

CREATE INDEX "IX_Reservation_EventId" ON "Reservation" ("EventId");

CREATE INDEX "IX_Reservation_SeatId" ON "Reservation" ("SeatId");

CREATE INDEX "IX_Reservation_UserId" ON "Reservation" ("UserId");

CREATE INDEX "IX_Seat_LayoutId" ON "Seat" ("LayoutId");

CREATE INDEX "IX_Layout_VenueId" ON "Layout" ("VenueId");

CREATE INDEX "IX_Venue_CityId" ON "Venue" ("CityId");

CREATE INDEX "IX_Venue_UserId" ON "Venue" ("UserId");

CREATE INDEX "IX_VenueCategory_CategoryId" ON "VenueCategory" ("CategoryId");

CREATE INDEX "IX_VenueCategory_VenueId" ON "VenueCategory" ("VenueId");

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260525170716_InitialCreate', '9.0.1');

CREATE TABLE "NonSelectable" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "LayoutId" integer NOT NULL,
    "X" numeric NOT NULL,
    "Y" numeric NOT NULL,
    "Width" numeric NOT NULL,
    "Height" numeric NOT NULL,
    "ShapeType" text,
    "BackgroundColor" text,
    "Name" text,
    "Scene" boolean NOT NULL,
    CONSTRAINT "PK_NonSelectable" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_NonSelectable_Layout_LayoutId" FOREIGN KEY ("LayoutId") REFERENCES "Layout" ("Id") ON DELETE RESTRICT
);

CREATE INDEX "IX_NonSelectable_LayoutId" ON "NonSelectable" ("LayoutId");

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260529060324_AddShapesToNonSelectables', '9.0.1');

ALTER TABLE "Seat" ADD "Height" numeric;

ALTER TABLE "Seat" ADD "Width" numeric;

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260529130225_AddSeatDimensions', '9.0.1');

ALTER TABLE "Event" ADD "Description" text;

ALTER TABLE "Event" ADD "OrganizerId" text;

CREATE TABLE "EventImage" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "EventId" integer NOT NULL,
    "ImagePath" text,
    "DisplayOrder" integer NOT NULL,
    CONSTRAINT "PK_EventImage" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_EventImage_Event_EventId" FOREIGN KEY ("EventId") REFERENCES "Event" ("Id") ON DELETE RESTRICT
);

CREATE INDEX "IX_Event_OrganizerId" ON "Event" ("OrganizerId");

CREATE INDEX "IX_EventImage_EventId" ON "EventImage" ("EventId");

ALTER TABLE "Event" ADD CONSTRAINT "FK_Event_AspNetUsers_OrganizerId" FOREIGN KEY ("OrganizerId") REFERENCES "AspNetUsers" ("Id") ON DELETE RESTRICT;

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260602124409_AddEventOrganizer', '9.0.1');

ALTER TABLE "EventType" ADD "ImagePath" text;

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260730081840_EventTypeImage', '9.0.1');

ALTER TABLE "Event" ALTER COLUMN "VenueId" DROP NOT NULL;

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260730115911_NoMainEventLocations', '9.0.1');

ALTER TABLE "Seat" ADD "UnitGrouId" integer;

ALTER TABLE "Seat" ADD "UnitGroupId" integer;

ALTER TABLE "NonSelectable" ADD "UnitGrouId" integer;

ALTER TABLE "NonSelectable" ADD "UnitGroupId" integer;

CREATE TABLE "UnitGroup" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Name" text,
    "Top" numeric NOT NULL,
    "Left" numeric NOT NULL,
    "LayoutId" integer NOT NULL,
    CONSTRAINT "PK_UnitGroup" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_UnitGroup_Layout_LayoutId" FOREIGN KEY ("LayoutId") REFERENCES "Layout" ("Id") ON DELETE RESTRICT
);

CREATE INDEX "IX_Seat_UnitGrouId" ON "Seat" ("UnitGrouId");

CREATE INDEX "IX_NonSelectable_UnitGrouId" ON "NonSelectable" ("UnitGrouId");

CREATE INDEX "IX_UnitGroup_LayoutId" ON "UnitGroup" ("LayoutId");

ALTER TABLE "NonSelectable" ADD CONSTRAINT "FK_NonSelectable_UnitGroup_UnitGrouId" FOREIGN KEY ("UnitGrouId") REFERENCES "UnitGroup" ("Id") ON DELETE RESTRICT;

ALTER TABLE "Seat" ADD CONSTRAINT "FK_Seat_UnitGroup_UnitGrouId" FOREIGN KEY ("UnitGrouId") REFERENCES "UnitGroup" ("Id") ON DELETE RESTRICT;

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260731172803_AddUnitGroups', '9.0.1');

CREATE TABLE "Wishlist" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "UserId" text,
    "EventId" integer NOT NULL,
    CONSTRAINT "PK_Wishlist" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Wishlist_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES "AspNetUsers" ("Id") ON DELETE RESTRICT,
    CONSTRAINT "FK_Wishlist_Event_EventId" FOREIGN KEY ("EventId") REFERENCES "Event" ("Id") ON DELETE RESTRICT
);

CREATE INDEX "IX_Wishlist_EventId" ON "Wishlist" ("EventId");

CREATE INDEX "IX_Wishlist_UserId" ON "Wishlist" ("UserId");

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260804064314_addedWishlist', '9.0.1');

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260813084855_newLayoutScheme', '9.0.1');

ALTER TABLE "Event" RENAME COLUMN "SubAreaId" TO "LayoutId";

ALTER INDEX "IX_Event_SubAreaId" RENAME TO "IX_Event_LayoutId";

ALTER TABLE "SubArea" RENAME TO "Layout";

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260813090846_RenameSubAreaToLayout', '9.0.1');

COMMIT;

